//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KDBits.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STRING_RES_NAME             101
#define IDS_STRING_RES_SIZE             102
#define IDD_RESLISTPAGE                 103
#define IDS_STRING_RES_TIME             103
#define IDS_STRING_RES_RULE             104
#define IDS_STRING_RES_STATE            105
#define IDS_STRING_RES_TYPE             106
#define IDS_STRING_RES_VER              107
#define IDS_STRING_INSTALL_PATH         108
#define IDS_STRING_RULE_AUTOMATIC       109
#define IDS_STRING_RULE_MANUAL          110
#define IDD_CONFIGNETWORK               111
#define IDS_STRING_TITLE_NETGAME        111
#define IDD_CONFIGDISK                  112
#define IDS_STRING_TITLE_LOCALGAME      112
#define IDD_CONFIGPATH                  113
#define IDS_STRING_TITLE_OTHER          113
#define IDD_STARTUPDLG                  114
#define IDS_STRING_APPLICATION_TITLE    114
#define IDS_STRING_PATH_NETGAME         115
#define IDS_STRING_PATH_LOCALGAME       116
#define IDS_STRING_PATH_OTHER           117
#define IDD_DOWNLOADLISTPAGE            118
#define IDS_STRING_TITLE_DOWNLOADLIST   118
#define IDS_STRING_DOWNLOADLIST_NAME    119
#define IDS_STRING_DOWNLOADLIST_TYPE    120
#define IDS_STRING_DOWNLOADLIST_PATH    121
#define IDS_STRING_DOWNLOADLIST_STATE   122
#define IDS_STRING_DOWNLOADLIST_PROGRESS 123
#define IDS_STRING_DOWNLOADLIST_DOWNSPEED 124
#define IDS_STRING_DOWNLOADLIST_UPSPEED 125
#define IDS_STRING_DOWNLOADLIST_SIZE    126
#define IDS_STRING_DOWNLOADLIST_DOWNEDSIZE 127
#define IDR_MAINFRAME                   128
#define IDR_KDBitsTYPE                  129
#define IDS_STRING_DOWNLOADLIST_UPEDSIZE 129
#define IDD_PREDOWNLOADGENERALPAGE      130
#define IDS_STRING_FILE_NAME            130
#define IDD_PREDOWNLOADDLG              131
#define IDS_STRING_FILE_SIZE            131
#define IDB_DISABLE                     132
#define IDB_NORMAL                      133
#define IDR_MENU_RESLIST_POP            134
#define IDD_DIALOG_DOWNLOAD_SELECT      135
#define IDS_STRING_DOWNLOADLIST_HEALTH  136
#define IDS_STRING_DOWNLOADLIST_PEERS   137
#define IDR_MENU_DOWNLIST_POP           137
#define IDS_STRING_DOWNLOADLIST_SEEDS   138
#define IDD_PREDOWNLOADOTHERPAGE        139
#define IDD_PREDOWNLOADSETUPPAGE        140
#define IDD_PREDELETEDOWNNODEDLG        141
#define IDD_GENERALOUTPUTPAGE           142
#define IDD_PEERLISTPAGE                143
#define IDD_MAKETORRENTFILEDLG          144
#define IDD_ASYNWAITDLG                 145
#define IDC_NETGAMELIST                 1001
#define IDC_EDIT_PATH                   1001
#define IDC_BUTTON_BROWSE               1003
#define IDC_COMBO_UPDATERULE            1004
#define IDC_LIST_DOWNLOADLIST_SELECT    1005
#define IDC_STARTUPDLG_PROGRESS         1006
#define IDC_STARTUPDLG_STATIC           1007
#define IDC_DOWNLOADLIST                1008
#define IDC_PROGRESS_DOWNLOADSEED       1009
#define IDC_STATIC_DOWNLOADSEED         1010
#define IDC_BUTTON1                     1011
#define IDC_GENERAL_BROWER              1011
#define IDC_EDIT1                       1012
#define IDC_NETGAME_PATH                1012
#define IDC_LIST1                       1013
#define IDC_EDIT3                       1013
#define IDC_GENERAL_FILELIST            1013
#define IDC_OTHER_CREATOR               1013
#define IDC_LOCALGAME_PATH              1013
#define IDC_DELETEDOWNNODE_NODELIST_LIST 1013
#define IDC_MKT_URL_LIST_EDIT           1013
#define IDC_EDIT2                       1014
#define IDC_EDIT6                       1014
#define IDC_LISTEN_PORT                 1014
#define IDC_OTHER_PATH                  1014
#define IDC_MKT_CREATOR_EDIT            1014
#define IDC_EDIT4                       1015
#define IDC_OTHER_COMMENT               1015
#define IDC_PROXY_IP_EDIT               1015
#define IDC_MKT_COMMENT_EDIT            1015
#define IDC_EDIT5                       1016
#define IDC_GENERAL_SAVEPATH            1016
#define IDC_OTHER_URLLIST               1016
#define IDC_PROXY_PORT_EDIT             1016
#define IDC_GENERAL_DISKSIZE            1017
#define IDC_EDIT7                       1017
#define IDC_PROXY_USERNAME_EDIT         1017
#define IDC_GENERAL_NAME                1018
#define IDC_EDIT8                       1018
#define IDC_PROXY_PASSWORD_EDIT         1018
#define IDC_GENERAL_SIZE                1019
#define IDC_SPIN1                       1020
#define IDC_UPLOADLIMIT_SPIN            1020
#define IDC_SPIN2                       1021
#define IDC_DOWNLIMIT_SPIN              1021
#define IDC_SPIN3                       1022
#define IDC_LISTEN_PORT_SPIN            1022
#define IDC_CHECK2                      1024
#define IDC_OPEN_UPNP_CHECK             1024
#define IDC_COMBO1                      1025
#define IDC_PROXY_TYPE_COMBO            1025
#define IDC_SETUP_RUNSETUP_COMBO        1025
#define IDC_MKT_DIRORFILE_COMBO         1025
#define IDC_CHECK3                      1026
#define IDC_PROXY_IS_VALIDATE_CHECK     1026
#define IDC_CONFIGDISK_PROTECTSIZE_COMBO 1026
#define IDC_CHECK4                      1027
#define IDC_JOIN_DHT_CHECK              1027
#define IDC_NETGAME_BRW                 1027
#define IDC_UPLOADLIMIT                 1028
#define IDC_LOCALGAME_BRW               1028
#define IDC_CONFIGDISK_DEFACLIENT_CHECKBOX 1028
#define IDC_DOWNLIMIT                   1029
#define IDC_OTHER_BRW                   1029
#define IDC_CONFIGDISK_AUTORUN_CHECKBOX 1029
#define IDC_SETUP_UPLOADLIMIT           1030
#define IDC_CONFIGDISK_DISKCACHE_COMBO  1030
#define IDC_SETUP_UPLOADLIMIT_SPIN      1031
#define IDC_CONFIGDISK_CHECKUPDATE_CHECKBOX 1031
#define IDC_SETUP_DOWNLIMIT             1032
#define IDC_CONFIGDISK_MAXTASK_EDIT     1032
#define IDC_SETUP_DOWNLIMIT_SPIN        1033
#define IDC_CONFIGDISK_CHECKDATACALESUM_CHECKBOX 1033
#define IDC_CONFIGDISK_PREALLOC_CHECKBOX 1035
#define IDC_CONFIGDISK_DELFILE_CHECKBOX 1036
#define IDC_CONFIGDISK_RUNSETUP_COMBO   1037
#define IDC_CONFIGDISK_MAXTASK_SPIN     1038
#define IDC_DELETEDOWNNODE_DELEFILE_CHECK 1039
#define IDC_SETUP_PREALLOC_CHECKBOX     1041
#define IDC_STATIC_CHECKDATACALESUM     1042
#define IDC_MKT_ALLOW_DHT_RADIO         1044
#define IDC_MKT_UNALLOW_DHT_RADIO       1045
#define IDC_MKT_PATH_EDIT               1046
#define IDC_MKT_BRW_BUTTON              1047
#define IDC_MKT_PIECESIZE_COMBO         1048
#define IDC_ASYNWAITDLG_STATIC          1049
#define IDC_MKT_TITLE_STATIC            1050
#define ID_ASDSD_ASDSAD                 32771
#define ID_ASDSD_ASDA                   32772
#define ID_RES_DOWN                     32773
#define ID_RES_DOWNLOAD                 32774
#define ID_RES_                         32775
#define ID_RES_PROPERTY                 32776
#define ID_Menu                         32777
#define ID_32778                        32778
#define ID_32779                        32779
#define ID_32780                        32780
#define ID_32781                        32781
#define ID_MAIN_MENU_MAKEFILE           32782
#define ID_MAIN_MENU_CONFIG             32783
#define ID_MAIN_MENU_DELETE             32786
#define ID_MAIN_MENU_START_ALL          32787
#define ID_MAIN_MENU_STOP_ALL           32788
#define ID_MAIN_MENU_DELETE_ALL         32789
#define ID_MAIN_MENU_NEW_TASK           32790
#define ID_MAIN_MENU_LOAD_GAMELIST      32792
#define ID_MENU_DOWNLIST_START_TASK     32802
#define ID_MENU_DOWNLIST_STOP_TASK      32803
#define ID_MENU_DOWNLIST_DELETE_TASK    32805
#define ID_MENU_DOWNLIST_ANNOUNCE_TASK  32806
#define ID_MENU_DOWNLIST_TORRENT_FILE_SAVE 32807
#define ID_MENU_DOWNLIST_OPEN_DIR       32808
#define ID_MENU_DOWNLIST_TASK_PROPERTY  32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           146
#endif
#endif
